### PR TITLE
Rename translations dir to resolve upcoming hass incompatibility

### PR DESCRIPTION
**Pull request by tmcarr**
Got an error on the latest beta of hass:

>     eventsensor: the ‘.translations’ directory has been moved, the new name is ‘translations’, starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 

Figured I'd offer a patch.

### CODE REVIEW

**Comment by azogue** [comment]
**Nice!** I didn't know this!

@tmcarr , does that change work for the current version, v0.108.x?

**Comment by tmcarr** [comment]
Actually it doesn't, I just went digging, this is 0.109 specific it seems. 
https://github.com/home-assistant/core/pull/34494

**Comment by azogue** [comment]
> Actually it doesn't, I just went digging, this is 0.109 specific it seems.
> [home-assistant/core#34494](https://github.com/home-assistant/core/pull/34494)

Then we should also increase the HA minimum version to 109 in the HACS manifest and wait for the new release to merge it, don't you think?

**Comment by azogue** [comment]
I'm merging this and I'll do the minimal changes over in another PR, ok?

Thanks!

**Comment by tmcarr** [comment]
Sorry for not replying soon enough, yeah I didn't know what that format was etc, thanks for merging and fixing.

**Pull request merged**
